baseURL = ""
languageCode = "en-us"
title = "Infinity Comming Soon Template By Themefisher"
theme = "infinity-hugo"

[params]

    # Navigation
    [params.navigation]
        logo = "images/logo.png"
        home = "Home"
        about = "About"
        service = "Services"
        contact = "Contact"

    # Hero Area
    [params.hero]
        enable      = true
        bg          = "images/bg.jpg"
        logo =        "images/southerntinyweb.png"
       # title       = "BRING YOUR PRODUCT TO LIGHT"
       # subtitle    = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna"
       # btnText     = "Get Started"
       # countdownYear = "2019"
       # countdownMonth = "12"
       # countdownDay  = "27"

    # About Section
    [params.about]
        enable      = true
        heading     = "We offer design services and will tailor your home to customer specification."
        description = "Here at Southern, our seasoned faculty and construction management students pour skill and talent into each Southern Tiny Living house. Under supervision, they carefully implement all that is learned in class - right on the job! "

        [[params.about.sliderItem]]
            image   = "images/stove.jpg"
        [[params.about.sliderItem]]
           image   = "images/outside.jpg"
        [[params.about.sliderItem]]
           image   = "images/bathtub.jpg"

    
    # Service Section
    [params.service]
        enable      = true
        title       = "Find Better Solutions Build Better Products"
        subtitle    = "Our building practices are NOAHcertified.org inspected and meet IRC 2018 building code standards"
        [[params.service.serviceItem]]
            # give icon(themefisher icon font), title, description
            # more about themefisher icon font visit https://github.com/themefisher/themefisher-font
            # use delay for reveal items one by one
            icon    = "tf-strategy"
            title   = "Tailor Designs"
            description = "We offer design services and will tailor your home to customer specification."
            delay   = "0s"

        [[params.service.serviceItem]]
            # give icon(themefisher icon font), title, description
            # more about themefisher icon font visit https://github.com/themefisher/themefisher-font
            # use delay for reveal items one by one
            icon    = "tf-circle-compass"
            title   = "Simple-living."
            description = "Strong, energy efficient Tiny Homes that won't require your sacrifice of comfort for simple-living"
            delay   = "0.2s"

        [[params.service.serviceItem]]
            # give icon(themefisher icon font), title, description
            # more about themefisher icon font visit https://github.com/themefisher/themefisher-font
            # use delay for reveal items one by one
            icon    = "tf-anchor2"
            title   = "Tons of Feature"
            description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
            delay   = "0.4s"

        [[params.service.serviceItem]]
            # give icon(themefisher icon font), title, description
            # more about themefisher icon font visit https://github.com/themefisher/themefisher-font
            # use delay for reveal items one by one
            icon    = "tf-globe"
            title   = "NOAH certified"
            description = "Our building practices are NOAHcertified.org inspected and meet IRC 2018 building code standards"
            delay   = "0.6s"

    # NEw demo photo Section


    
    # Call to Action Section
    [params.cta]
        enable      = true
        bg          = "images/call-to-action.jpg"
        title       = "SCHEDULE A VISIT"
        subtitle    = "See the exterior and interior portions of the tiny house in person."

    [params.contact]
        enable      = true
        title       = "Get In Touch"
        subtitle    = "Contact us if you have additional questions, need to schedule a special appointment, or need additional purchase information."
